services:
  bash:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASH_VERSION: "${BASH_VERSION}"
    volumes:
      - "${MOUNT_DIR}:/tmp/lib"
    working_dir: "/tmp/lib"
    tty: true
